spring:
  application:
    name: reserve

  datasource:
    url: jdbc:mysql://localhost:3306/reserve?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # 1. 여기서 true로 설정하면 표준 출력(System.out)으로 쿼리가 나옵니다.
    # 로거(logging.level)와 중복될 수 있으므로 로그 양을 줄이려면 false를 권장합니다.
    show-sql: true
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 운영에서는 validate 권장
    properties:
      hibernate:
        format_sql: true # 쿼리를 예쁘게 정렬
        highlight_sql: true # (선택) 콘솔에 색상 추가

  server:
    port: 8080

  logging:
    level:
      root: info
      org.hibernate.SQL: debug
      # 패키지 범위를 넓히고 하이버네이트 결과값까지 확인
      org.hibernate.orm.jdbc: trace
      org.hibernate.resource.jdbc: trace

